[package]

name = "ev3dev"
version = "0.0.1"
authors = ["Rick Poyner <rico@alum.mit.edu>"]

[dependencies.hamcrest]

git = "https://github.com/carllerche/hamcrest-rust.git"

#[dependencies]
#clippy = "*"
